apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-sample-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sluetzen-tenant/python-sample-app/python-sample-component@sha256:c30e4007c51b41d4cedab7d2bb02f82fc5abfb5c3abecb40cbfd682371af2b4d
        name: my-python
        resources: {}
status: {}
