apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sluetzen-tenant/python-sample-app/devfile-sample@sha256:c7fefe0aebdcc80ae741fb90e7bfbc483d9ed719a820d5549dc85a233f074a28
        name: my-nodejs
        resources: {}
status: {}
