apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-sample-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-sample-component
    app.kubernetes.io/part-of: python-sample-app
  name: python-sample-component
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-sample-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-sample-component
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sluetzen-tenant/python-sample-app/python-sample-component@sha256:387d2f0a8de5834f7d75b1c2125bdd01a83481e6b874543c2df52cc6d5a56f11
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
